# Generated by Django 4.1.3 on 2022-11-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyPage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transtation_id',
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
